---
title: "Mouse and Rat glioblastoma models"
author: "Stefan Loska"
date: "March 14, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, libraries}
library(oligo)
library(Biobase)
library(AnnotationDbi)
```

# Get expression

## Reading data

Read data from cel files and probe annotation file.

```{r }
read_cel <- function(data_dir, s_info, skip = NULL){
  # get sample meta data
  tab <- read.delim(paste(data_dir, s_info, sep = "/"), colClasses = c("character", "factor", "character"))
  rownames(tab) <- tab$filename
  # check sample_info vs. cel files
  if (! setequal(tab$filename, list.celfiles(data_dir))) stop("sample info file doesn't fit available cel files")

  # skip what is meant to skip
  tab <- tab[!rownames(tab) %in% skip,]

  # get microarray signal
  ab <- read.celfiles(filenames = paste(data_dir, tab$filename, sep = "/"), phenoData = AnnotatedDataFrame(tab))
  ab
}
```


## Preprocessing

RMA

```{r }
rma_core <- function(ab){
  R <- oligo::rma(ab, target = "core")
  R
}
```


## Annotation

Get annotation and remove probes mapping to more than one gene.

```{r }
annotate <- function(R, annot){
  # choose columns for feature data
  fd <- select(annot, keys = rownames(R), keytype = "PROBEID", columns = c("ENTREZID", "SYMBOL", "GENENAME"))
  
  fd <- fd[!is.na(fd$ENTREZID),]
  
  freq <- table(fd$PROBEID)
  dambg <- names(freq)[freq == 1]
  fd <- fd[fd$PROBEID %in% dambg, ]
  rownames(fd) <- fd$PROBEID
  
  R <- R[rownames(fd)]
  fData(R) <- fd
  
  R
}

```

Pick up one probe for each gene. This will be the probe with the highest variance among samples.

```{r}
dedegen <- function(R){
  # keep only one probeset per gene; this will be the one with highest variance
  sel <- tapply(seq_along(fData(R)$ENTREZID), fData(R)$ENTREZID, c)
  
  sel <- tapply(seq_along(fData(R)$ENTREZID), fData(R)$ENTREZID, function(x){
    if (length(x) == 1) x else{
      vars <- apply(exprs(R)[x,], 1, var, na.rm = T)
      x[which.max(vars)]
    }
  })
  
  sel <- as.vector(sel)
  
  R <- R[sel,]
  R
}

```

Convert to human.

```{r}
to_human <- function(R, hom, taxid){
  # restric to human and taxid
  hom <- hom[hom$tax %in% c("9606", taxid),]
  
  # remove disambiguities (and no pair), i.e. for each id need exactly one human and one taxid gene
  sel <- tapply(hom$tax, hom$id, function(x){
    length(x) == 2 & length(unique(x)) == 2
  })
  sel <- names(sel)[sel]
  hom <- hom[hom$id %in% sel,]
  
  # convert fData
  ids <- hom$id[match(fData(R)$ENTREZID, hom$entrez)]
  ens <- hom$entrez[match(ids, hom$id)]
  
  fData(R)$HUMENTREZID <- ens
  R <- R[!is.na(fData(R)$HUMENTREZID),]
  rownames(R) <- fData(R)$HUMENTREZID
  
  R
}

```

## Get expression

```{r}
get_exprs <- function(data_dir, s_info, skip = NULL, annot, hom, taxid){
  ab <- read_cel(data_dir, s_info, skip)
  R <- rma_core(ab)
  R <- annotate(R, annot)
  R <- dedegen(R)
  R <- to_human(R, hom, taxid)
  R
}

```


# Analysis

```{r}
download.file("ftp://ftp.ncbi.nih.gov/pub/HomoloGene/build68/homologene.data", "homologene.data")
hom <- read.delim("homologene.data", header = F,
                  colClasses = c("character", "character", "character", "NULL", "NULL", "NULL"),
                  col.names = c("id", "tax", "entrez", "NULL", "NULL", "NULL"))

Rat <- get_exprs(data_dir = "Rat_data", 
          s_info = "sample_info.txt", 
          annot = ragene21sttranscriptcluster.db::ragene21sttranscriptcluster.db, 
          hom = hom, 
          taxid = "10116")

Mouse <- get_exprs(data_dir = "Mouse_data", 
          s_info = "sample_info.txt", 
          annot = mogene21sttranscriptcluster.db::mogene21sttranscriptcluster.db, 
          hom = hom, 
          taxid = "10090")

```








